branch-defaults:
  main:
    environment: slack-clone-prod
    group_suffix: null
global:
  application_name: slack-clone
  default_ec2_keyname: null
  default_platform: Node.js 18
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
